services:
  - type: web
    name: scheduler-jump
    env: node
    buildCommand: |
      if [ -z "$GOOGLE_CLIENT_ID" ] || [ -z "$GOOGLE_CLIENT_SECRET" ] || [ -z "$NEXTAUTH_URL" ] || [ -z "$NEXTAUTH_SECRET" ]; then
        echo "Error: Required environment variables are not set"
        echo "GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:+set}${GOOGLE_CLIENT_ID:-not set}"
        echo "GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:+set}${GOOGLE_CLIENT_SECRET:-not set}"
        echo "NEXTAUTH_URL: ${NEXTAUTH_URL:+set}${NEXTAUTH_URL:-not set}"
        echo "NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:+set}${NEXTAUTH_SECRET:-not set}"
        exit 1
      fi
      npm install
      npx prisma generate
      echo "Pushing database schema..."
      npx prisma db push --accept-data-loss --force-reset
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://jump-scheduling-app-2.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: scheduler-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HUBSPOT_ACCESS_TOKEN
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: LINKEDIN_CLIENT_ID
        sync: false
      - key: LINKEDIN_CLIENT_SECRET
        sync: false
      - key: LINKEDIN_REDIRECT_URI
        value: https://jump-scheduling-app-2.onrender.com/api/linkedin/callback

databases:
  - name: scheduler-db
    plan: free 