services:
  - type: web
    name: scheduler-jump
    env: node
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma db push --accept-data-loss
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://jump-scheduling-app-2.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: scheduler-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true

databases:
  - name: scheduler-db
    plan: free 