services:
  - type: web
    name: scheduler-jump
    env: node
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: scheduler-db
          property: connectionString

databases:
  - name: scheduler-db
    plan: free 