services:
  - type: web
    name: scheduler-jump
    env: node
    buildCommand: NODE_ENV=production npm ci && npx prisma generate && npx prisma migrate deploy && NEXT_TELEMETRY_DISABLED=1 npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: scheduler-db
          property: connectionString

databases:
  - name: scheduler-db
    plan: free 