services:
  - type: web
    name: scheduler-jump
    env: node
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma db push --accept-data-loss
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://jump-scheduling-app-2.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: scheduler-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: HUBSPOT_ACCESS_TOKEN
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: LINKEDIN_CLIENT_ID
        sync: false
      - key: LINKEDIN_CLIENT_SECRET
        sync: false
      - key: LINKEDIN_REDIRECT_URI
        value: https://jump-scheduling-app-2.onrender.com/api/linkedin/callback

databases:
  - name: scheduler-db
    plan: free 